# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:36
from video.models import TaggedVideo
from django.core.management.base import BaseCommand
from django.core.files import File 
import os

class Command(BaseCommand):
    help = 'Ingest tagged videos from a directory'

    def add_arguments(self, parser):
        parser.add_argument('category', nargs=1, type=str)
        parser.add_argument('videofile', nargs='+', type=str)

    def handle(self, *args, **options):

        mgr = TaggedVideo.objects

        category = options['category'][0]

        for videofile in options['videofile']:

            # tag is the file basename
            tag, _ext = os.path.splitext(os.path.basename(videofile))

            with open(videofile, 'rb') as fd:
                thefile = File(fd, name=videofile)
                tv = mgr.add(category, tag, thefile)
                # access the poster_url to force generation of thumbnail
                tv.poster_url()

            self.stdout.write(self.style.SUCCESS('Successfully ingested "{}" to {}'.format(videofile, str(tv))))
