# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
