# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taggedvideo',
            unique_together=set([('category', 'tag')]),
        ),
    ]
