# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='video.TaggedVideo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Version'),
        ),
    ]
