# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170423_2100'),
    ]

    def category_to_contenttype(apps, schema_editor):
        # Try to connect category to ContentType, if not possible, use ContentType of TaggedVideo.
        ContentType = apps.get_model('contenttypes', 'ContentType')
        TaggedVideo = apps.get_model('video', 'TaggedVideo')
        taggedvideo_ct = ContentType.objects.get_for_model(TaggedVideo)
        for tagvid in TaggedVideo.objects.all():
            try:
                # Try to match the TagVideo.category with a model name.
                # It can fail if model names collide with apps.
                ct = ContentType.objects.get(model__iexact=tagvid.category)
            except:
                # If it fails, set the ContentType to TaggedVideo's. Because what else?
                ct = taggedvideo_ct
            tagvid.category = ct
            tagvid.save()

    operations = [
        migrations.AlterField(
            model_name='taggedvideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedvideo',
            name='tag',
            field=models.PositiveIntegerField(db_index=True, verbose_name='object id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(storage=video.models.TaggedVideoStorage(), upload_to='video', verbose_name='video file'),
        ),
        migrations.RunPython(category_to_contenttype),
    ]
