# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('video', '0003_auto_20170822_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggedvideo',
            old_name='category',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='taggedvideo',
            old_name='tag',
            new_name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='taggedvideo',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
